<script setup lang="ts">
import router from "@/router";
import { useUserStore } from "@/stores/user";
import { formatDate } from "@/utils/formatDate";
import { storeToRefs } from "pinia";
import { onBeforeMount, ref } from "vue";
import { fetchy } from "../../utils/fetchy";
import ContextInPostComponent from "../Context/ContextInPostComponent.vue";
import VoteComponent from "../VoteComponent.vue";

const props = defineProps(["post", "showButtons"]);
const emit = defineEmits(["editPost", "refreshPosts", "openContexts"]);
const { currentUsername } = storeToRefs(useUserStore());

const showButtons = ref(props.showButtons);
const context = ref<Record<string, string>>();
const loaded = ref(false);

const deletePost = async () => {
  try {
    await fetchy(`api/posts/${props.post._id}`, "DELETE");
  } catch {
    return;
  }
  emit("refreshPosts");
};

function openUser() {
  if (props.post.author !== "Autogenerated") {
    void router.push({ path: "/user", query: { username: props.post.author } });
  }
}

function openContext() {
  void router.push({ path: "/context", query: { id: props.post._id } });
}

async function getTopContext() {
  try {
    const topCtx = await fetchy(`api/upvotes/posts/${props.post._id}`, "GET");
    context.value = topCtx.item;
  } catch {
    return;
  }
}

onBeforeMount(async () => {
  await getTopContext();
  loaded.value = true;
});
</script>

<template>
  <p @click="openUser" class="author">{{ props.post.author }}</p>
  <button v-if="showButtons" @click="openContext">Open Contexts</button>
  <p>{{ props.post.content }}</p>
  <div class="base">
    <menu v-if="props.post.author == currentUsername && showButtons">
      <li><button class="btn-small pure-button" @click="emit('editPost', props.post._id)">Edit</button></li>
      <li><button class="button-error btn-small pure-button" @click="deletePost">Delete</button></li>
    </menu>
    <article class="timestamp">
      <p v-if="props.post.dateCreated !== props.post.dateUpdated">Edited on: {{ formatDate(props.post.dateUpdated) }}</p>
      <p v-else>Created on: {{ formatDate(props.post.dateCreated) }}</p>
    </article>
  </div>
  <ContextInPostComponent v-if="loaded && showButtons" :context="context" />
  <VoteComponent v-if="showButtons" :item-id="$props.post._id" />
</template>

<style scoped>
p {
  margin: 0em;
}

.author {
  font-weight: bold;
  font-size: 1.2em;
}

menu {
  list-style-type: none;
  display: flex;
  flex-direction: row;
  gap: 1em;
  padding: 0;
  margin: 0;
}

.timestamp {
  display: flex;
  justify-content: flex-end;
  font-size: 0.9em;
  font-style: italic;
}

.base {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.base article:only-child {
  margin-left: auto;
}
</style>
