import { User } from "./app";
import { ContextDoc } from "./concepts/context";
import { AlreadyFollowingError, FollowDoc, FollowNotFoundError } from "./concepts/follow";
import { AlreadyFriendsError, FriendNotFoundError, FriendRequestAlreadyExistsError, FriendRequestDoc, FriendRequestNotFoundError } from "./concepts/friend";
import { PostAuthorNotMatchError, PostDoc } from "./concepts/post";
import { AlreadyUpvotedError, NotUpvotedError } from "./concepts/upvote";
import { Router } from "./framework/router";

/**
 * This class does useful conversions for the frontend.
 * For example, it converts a {@link PostDoc} into a more readable format for the frontend.
 */
export default class Responses {
  /**
   * Convert PostDoc into more readable format for the frontend by converting the author id into a username.
   */
  static async post(post: PostDoc | null) {
    if (!post) {
      return post;
    }
    const author = await User.getUserById(post.author);
    return { ...post, author: author.username };
  }

  /**
   * Same as {@link post} but for an array of PostDoc for improved performance.
   */
  static async posts(posts: PostDoc[]) {
    const authors = await User.idsToUsernames(posts.map((post) => post.author));
    return posts.map((post, i) => ({ ...post, author: authors[i] }));
  }

  /**
   * Convert ContextDoc into more readable format for the frontend by converting the author id into a username.
   */
  static async context(context: ContextDoc | null) {
    if (!context) {
      return context;
    }

    if (context.author) {
      const author = await User.getUserById(context.author);
      return { ...context, author: author.username };
    } else {
      return { ...context, author: "Autogenerated" };
    }
  }

  /**
   * Same as {@link context} but for an array of ContextDoc.
   */
  static async contexts(contexts: ContextDoc[]) {
    const names = [];
    for (const context of contexts) {
      names.push(await this.context(context));
    }
    return names;
  }

  /**
   * Convert FriendRequestDoc into more readable format for the frontend
   * by converting the ids into usernames.
   */
  static async friendRequests(requests: FriendRequestDoc[]) {
    const from = requests.map((request) => request.from);
    const to = requests.map((request) => request.to);
    const usernames = await User.idsToUsernames(from.concat(to));
    return requests.map((request, i) => ({ ...request, from: usernames[i], to: usernames[i + requests.length] }));
  }

  static async following(follows: FollowDoc[]) {
    const followings = follows.map((f) => f.other);
    const usernames = await User.idsToUsernames(followings);
    return usernames;
  }

  static async followers(follows: FollowDoc[]) {
    const userFollowers = follows.map((f) => f.user);
    const usernames = await User.idsToUsernames(userFollowers);
    return usernames;
  }
}

Router.registerError(AlreadyUpvotedError, async (e) => {
  const username = (await User.getUserById(e.user)).username;
  return e.formatWith(username, e.target);
});

Router.registerError(NotUpvotedError, async (e) => {
  const username = (await User.getUserById(e.user)).username;
  return e.formatWith(username, e.target);
});

Router.registerError(PostAuthorNotMatchError, async (e) => {
  const username = (await User.getUserById(e.author)).username;
  return e.formatWith(username, e._id);
});

Router.registerError(FriendRequestAlreadyExistsError, async (e) => {
  const [user1, user2] = await Promise.all([User.getUserById(e.from), User.getUserById(e.to)]);
  return e.formatWith(user1.username, user2.username);
});

Router.registerError(FriendNotFoundError, async (e) => {
  const [user1, user2] = await Promise.all([User.getUserById(e.user1), User.getUserById(e.user2)]);
  return e.formatWith(user1.username, user2.username);
});

Router.registerError(FriendRequestNotFoundError, async (e) => {
  const [user1, user2] = await Promise.all([User.getUserById(e.from), User.getUserById(e.to)]);
  return e.formatWith(user1.username, user2.username);
});

Router.registerError(AlreadyFriendsError, async (e) => {
  const [user1, user2] = await Promise.all([User.getUserById(e.user1), User.getUserById(e.user2)]);
  return e.formatWith(user1.username, user2.username);
});

Router.registerError(FollowNotFoundError, async (e) => {
  const [user1, user2] = await Promise.all([User.getUserById(e.user), User.getUserById(e.other)]);
  return e.formatWith(user1.username, user2.username);
});

Router.registerError(AlreadyFollowingError, async (e) => {
  const [user1, user2] = await Promise.all([User.getUserById(e.user), User.getUserById(e.other)]);
  return e.formatWith(user1.username, user2.username);
});
