<script setup lang="ts">
import { useUserStore } from "@/stores/user";
import { formatDate } from "@/utils/formatDate";
import { storeToRefs } from "pinia";
import router from "../../router";
import { fetchy } from "../../utils/fetchy";
import VoteComponent from "../VoteComponent.vue";

const props = defineProps(["context"]);
const emit = defineEmits(["editContext", "refreshContexts"]);
const { currentUsername } = storeToRefs(useUserStore());

const deleteContext = async () => {
  try {
    await fetchy(`api/contexts/${props.context._id}`, "DELETE");
  } catch {
    return;
  }
  emit("refreshContexts");
};

function openUser() {
  if (props.context.author !== "Autogenerated") {
    void router.push({ path: "/user", query: { username: props.context.author } });
  }
}
</script>

<template>
  <div class="head">
    <p @click="openUser" class="author">{{ props.context.author }}</p>
    <menu v-if="props.context.author == currentUsername">
      <li><button class="btn-small pure-button" @click="emit('editContext', props.context._id)">Edit</button></li>
      <li><button class="button-error btn-small pure-button" @click="deleteContext">Delete</button></li>
    </menu>
  </div>
  <p>{{ props.context.content }}</p>
  <div class="base">
    <VoteComponent :item-id="$props.context._id" />
    <article class="timestamp">
      <p v-if="props.context.dateCreated !== props.context.dateUpdated">Edited on: {{ formatDate(props.context.dateUpdated) }}</p>
      <p v-else>Created on: {{ formatDate(props.context.dateCreated) }}</p>
    </article>
  </div>
</template>

<style scoped>
p {
  margin: 0em;
}

.author {
  font-weight: bold;
  font-size: 1.2em;
}

menu {
  list-style-type: none;
  display: flex;
  flex-direction: row;
  gap: 1em;
  padding: 0;
  margin: 0;
}

.head {
  display: flex;
  justify-content: space-between;
}

.timestamp {
  display: flex;
  justify-content: flex-end;
  font-size: 0.9em;
  font-style: italic;
}

.base {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.base article:only-child {
  margin-left: auto;
}
</style>
